// ─── TRAVEL OS SEED DATA ───
// Based on real trip: EZE → MNL → POM → PNG Tour → POM → MNL → ICN → Seoul → ICN → EZE
// Dates: Aug 10 – Sep 2, 2026 (~24 days)

import { type Trip, type City, type Task, type Reservation, type BudgetCategory, type Document, type PackingItem, type Alert, type Expense } from "@/lib/types/database";

const TRIP_ID = "550e8400-e29b-41d4-a716-446655440001";

// ─── TRIP ───
export const seedTrip: Omit<Trip, "user_id"> = {
  id: TRIP_ID,
  name: "Seúl + Papúa Nueva Guinea 2026",
  description: "Viaje cultural: Goroka Show con Wander Expeditions + 11 noches en Seúl. Ruta: EZE→GRU→DXB→MNL→POM→Tour PNG→POM→MNL→ICN→Seúl→ICN→DXB→GRU→EZE",
  destination: "Seoul, South Korea & Papua New Guinea",
  status: "planning",
  start_date: "2026-08-10",
  end_date: "2026-09-02",
  base_currency: "USD",
  total_budget: 7500,
  contingency_percent: 10,
  contingency_amount: 750,
  alert_days_warning: 7,
  alert_days_critical: 3,
  budget_warning_threshold: 80,
  budget_danger_threshold: 95,
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// ─── CITIES ───
export const seedCities: Omit<City, "id">[] = [
  { trip_id: TRIP_ID, name: "São Paulo (GRU)", country: "Brazil", arrival_date: "2026-08-10", departure_date: "2026-08-10", nights: 0, order_index: 0, notes: "Transit only" },
  { trip_id: TRIP_ID, name: "Dubai (DXB)", country: "UAE", arrival_date: "2026-08-11", departure_date: "2026-08-11", nights: 0, order_index: 1, notes: "Transit only" },
  { trip_id: TRIP_ID, name: "Manila (MNL)", country: "Philippines", arrival_date: "2026-08-11", departure_date: "2026-08-12", nights: 1, order_index: 2, notes: "Transit connection. Overnight before POM flight." },
  { trip_id: TRIP_ID, name: "Port Moresby (POM)", country: "Papua New Guinea", arrival_date: "2026-08-12", departure_date: "2026-08-14", nights: 2, order_index: 3, notes: "Pre-tour staging" },
  { trip_id: TRIP_ID, name: "PNG Highlands", country: "Papua New Guinea", arrival_date: "2026-08-14", departure_date: "2026-08-20", nights: 6, order_index: 4, notes: "Wander Expeditions PNG III Tour. Goroka Cultural Show. Asaro Mudmen, Skeleton Tribe, Dust Walkers homestays." },
  { trip_id: TRIP_ID, name: "Port Moresby (POM)", country: "Papua New Guinea", arrival_date: "2026-08-20", departure_date: "2026-08-21", nights: 1, order_index: 5, notes: "Post-tour, flight to MNL" },
  { trip_id: TRIP_ID, name: "Manila (MNL)", country: "Philippines", arrival_date: "2026-08-21", departure_date: "2026-08-22", nights: 1, order_index: 6, notes: "Transit. Connect to ICN flight." },
  { trip_id: TRIP_ID, name: "Seoul (ICN)", country: "South Korea", arrival_date: "2026-08-22", departure_date: "2026-09-02", nights: 11, order_index: 7, notes: "Jongno district Airbnb. Near Changgyeonggung Palace, Gwangjang Market, Bukchon Hanok Village." },
];

// ─── BUDGET CATEGORIES ───
// Labels en español por defecto (matchean dict t.budgetCategories.*). El código
// consumidor reemplaza con t.budgetCategories[category] cuando el locale lo dicta.
export const seedBudgetCategories: Omit<BudgetCategory, "id">[] = [
  { trip_id: TRIP_ID, category: "flights", label: "Vuelos", budgeted_amount: 2500, order_index: 0 },
  { trip_id: TRIP_ID, category: "accommodation", label: "Alojamiento", budgeted_amount: 900, order_index: 1 },
  { trip_id: TRIP_ID, category: "food", label: "Comida", budgeted_amount: 800, order_index: 2 },
  { trip_id: TRIP_ID, category: "transport", label: "Transporte interno", budgeted_amount: 300, order_index: 3 },
  { trip_id: TRIP_ID, category: "activities", label: "Actividades y tours", budgeted_amount: 3700, order_index: 4 },
  { trip_id: TRIP_ID, category: "insurance", label: "Seguro", budgeted_amount: 250, order_index: 5 },
  { trip_id: TRIP_ID, category: "connectivity", label: "Conectividad", budgeted_amount: 60, order_index: 6 },
  { trip_id: TRIP_ID, category: "shopping", label: "Compras", budgeted_amount: 200, order_index: 7 },
  { trip_id: TRIP_ID, category: "photography", label: "Fotografía/Tech", budgeted_amount: 100, order_index: 8 },
  { trip_id: TRIP_ID, category: "fees", label: "Comisiones y cambios", budgeted_amount: 150, order_index: 9 },
  { trip_id: TRIP_ID, category: "contingency", label: "Contingencia", budgeted_amount: 750, order_index: 10 },
  { trip_id: TRIP_ID, category: "other", label: "Otros", budgeted_amount: 100, order_index: 11 },
];

// ─── RESERVATIONS ───
export const seedReservations: Omit<Reservation, "id">[] = [
  {
    trip_id: TRIP_ID, type: "flight", criticality: "blocker", provider: "Emirates",
    city_id: null, city_name: "GRU→DXB→MNL + ICN→DXB→GRU",
    description: "Emirates NM6XKS. GRU→DXB→MNL 9 Ago + ICN→DXB→GRU 3 Sep. Turista Flex.",
    purchase_date: "2026-04-01", use_date: "2026-08-09", use_end_date: "2026-09-03",
    payment_deadline: null, original_amount: 9940, original_currency: "BRL",
    exchange_rate: 5.16, base_amount: 1927, status: "confirmed",
    confirmation_received: true, locator: "NM6XKS", link: null,
    contact: null, cancellation_policy: "Flex fare - changes allowed", is_cancellable: true,
    notes: "Paid with Black card. BRL 9,940.", created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    trip_id: TRIP_ID, type: "flight", criticality: "blocker", provider: "Philippine Airlines + Air Niugini",
    city_id: null, city_name: "MNL↔POM",
    description: "Booking 1124-604-505. PAL PR215 MNL→POM 12 Ago 00:20 + Air Niugini PX10 POM→MNL 21 Ago 16:20. Flex.",
    purchase_date: "2026-04-01", use_date: "2026-08-12", use_end_date: "2026-08-21",
    payment_deadline: null, original_amount: 734710, original_currency: "ARS",
    exchange_rate: 1200, base_amount: 612, status: "confirmed",
    confirmation_received: true, locator: "1124-604-505", link: null,
    contact: null, cancellation_policy: "Flex", is_cancellable: true,
    notes: "AR$734,710. Includes Air Niugini PX10 return (operator not recommended by Wander but only option for this route).",
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    trip_id: TRIP_ID, type: "flight", criticality: "blocker", provider: "Pending",
    city_id: null, city_name: "BUE↔GRU",
    description: "Buenos Aires to São Paulo. To be booked with credit card points (puntos TC).",
    purchase_date: null, use_date: "2026-08-09", use_end_date: "2026-09-03",
    payment_deadline: "2026-06-15", original_amount: 0, original_currency: "ARS",
    exchange_rate: 1, base_amount: 0, status: "pending",
    confirmation_received: false, locator: null, link: null,
    contact: null, cancellation_policy: null, is_cancellable: true,
    notes: "To be booked using credit card points. Priority purchase.", created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    trip_id: TRIP_ID, type: "flight", criticality: "blocker", provider: "Pending",
    city_id: null, city_name: "MNL→ICN",
    description: "Manila to Seoul/Incheon. ~Aug 22. To be purchased.",
    purchase_date: null, use_date: "2026-08-22", use_end_date: null,
    payment_deadline: "2026-06-30", original_amount: 0, original_currency: "USD",
    exchange_rate: 1, base_amount: 0, status: "pending",
    confirmation_received: false, locator: null, link: null,
    contact: null, cancellation_policy: null, is_cancellable: true,
    notes: "Pending purchase. Estimated ~USD 200-350.", created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    trip_id: TRIP_ID, type: "tour", criticality: "blocker", provider: "Wander Expeditions",
    city_id: null, city_name: "PNG Highlands",
    description: "PNG III Tour - Goroka Cultural Show. Homestays: Asaro Mudmen, Skeleton Tribe, Dust Walkers. Aug 14-20.",
    purchase_date: "2026-01-15", use_date: "2026-08-14", use_end_date: "2026-08-20",
    payment_deadline: null, original_amount: 3450, original_currency: "EUR",
    exchange_rate: 1.08, base_amount: 3726, status: "confirmed",
    confirmation_received: true, locator: null, link: null,
    contact: "Álvaro Rojas - Wander Expeditions", cancellation_policy: "Zero refund within 90 days of tour",
    is_cancellable: false, notes: "EUR 3,450 confirmed. Meals largely included during homestay days. Founded 2020, 700+ clients. Strict no-refund policy.",
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    trip_id: TRIP_ID, type: "accommodation", criticality: "essential", provider: "Airbnb",
    city_id: null, city_name: "Seoul",
    description: "Airbnb Jongno district. 11 nights (Aug 22 - Sep 2). Near Changgyeonggung Palace, Gwangjang Market, Bukchon Hanok Village.",
    purchase_date: "2026-03-15", use_date: "2026-08-22", use_end_date: "2026-09-02",
    payment_deadline: null, original_amount: 0, original_currency: "USD",
    exchange_rate: 1, base_amount: 0, status: "confirmed",
    confirmation_received: true, locator: null, link: null,
    contact: "Superhost - verified, legal registration", cancellation_policy: "requires_validation",
    is_cancellable: true, notes: "Strong value for August high season. AC needs verification with host. Amount requires_validation.",
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    trip_id: TRIP_ID, type: "insurance", criticality: "blocker", provider: "Pending",
    city_id: null, city_name: "All destinations",
    description: "Travel insurance with medical evacuation + direct GOP for PNG highlands. Trip cancellation coverage recommended.",
    purchase_date: null, use_date: "2026-08-10", use_end_date: "2026-09-02",
    payment_deadline: "2026-07-15", original_amount: 0, original_currency: "USD",
    exchange_rate: 1, base_amount: 0, status: "pending",
    confirmation_received: false, locator: null, link: null,
    contact: null, cancellation_policy: null, is_cancellable: true,
    notes: "Top options: IATI Mochilero, Heymondo TOP. Fallback: Assist365. MUST confirm GOP coverage for PNG in writing before purchase.",
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];

// ─── TASKS (70+) ───
export const seedTasks: Omit<Task, "id">[] = [
  // === FLIGHTS ===
  { trip_id: TRIP_ID, title: "Comprar pasajes BUE↔GRU con puntos", description: "Usar puntos de la tarjeta de crédito para Buenos Aires↔São Paulo", stage: "planning", category: "flights", subcategory: "booking", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-06-15", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: "Chequear disponibilidad de puntos y reservar", requires_payment: false, estimated_amount: 0, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Buenos Aires", notes: "Con puntos TC. Compra prioritaria.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Comprar pasaje MNL→ICN", description: "Manila a Seúl/Incheon, ~22 ago", stage: "planning", category: "flights", subcategory: "booking", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-06-30", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: "Comparar precios en Skyscanner/Google Flights", requires_payment: true, estimated_amount: 250, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Manila", notes: "Estimated USD 200-350", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Verificar detalles de la reserva Emirates", description: "Confirmar asiento, comidas, equipaje para NM6XKS", stage: "planning", category: "flights", subcategory: "preparation", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Entrar a Emirates y revisar la reserva", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Chequear reglas de equipaje PAL/Air Niugini", description: "Verificar franquicia para vuelos MNL↔POM", stage: "planning", category: "flights", subcategory: "preparation", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Revisar el sitio de la aerolínea", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Air Niugini not recommended by Wander but only option", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Check-in web Emirates GRU→DXB→MNL", description: null, stage: "pre_departure", category: "flights", subcategory: "check-in", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-07", due_date: "2026-08-09", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },

  // === INSURANCE ===
  { trip_id: TRIP_ID, title: "Investigar opciones de seguro de viaje", description: "Compare IATI Mochilero, Heymondo TOP, Assist365. Must have GOP for PNG highlands medevac.", stage: "planning", category: "insurance", subcategory: "research", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-06-01", status: "in_progress", progress: 50, is_blocker: true, dependency_id: null, next_action: "Request written GOP confirmation from top 2 providers", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "GOP = Guarantee of Payment. PNG helicopter medevac requires pre-auth before operators fly.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Confirmar cobertura GOP para PNG por escrito", description: "Get written confirmation that insurer provides direct GOP for medical evacuation in PNG highlands", stage: "planning", category: "insurance", subcategory: "confirmation", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-06-15", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: "Email top insurers requesting GOP details", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Non-negotiable requirement. Standard travel insurance may not suffice for PNG.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Comprar seguro de viaje", description: "Comprar la póliza elegida después de confirmar GOP", stage: "planning", category: "insurance", subcategory: "purchase", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: null, requires_payment: true, estimated_amount: 250, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Include trip cancellation coverage (non-refundable EUR 3,450 Wander tour)", updated_at: new Date().toISOString() },

  // === ACCOMMODATION ===
  { trip_id: TRIP_ID, title: "Confirmar aire acondicionado con el host de Seúl", description: "Verify air conditioning availability given Seoul's humid August conditions", stage: "planning", category: "accommodation", subcategory: "confirmation", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-05-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Mensaje al host de Airbnb", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "Superhost with high rating and legal registration", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Book Manila transit accommodation (night 1)", description: "Hotel cerca de MNL para la noche previa al vuelo POM 12-ago 00:20", stage: "planning", category: "accommodation", subcategory: "booking", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Buscar hoteles de aeropuerto en MNL", requires_payment: true, estimated_amount: 40, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Manila", notes: "Descansar antes del vuelo nocturno a POM", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Book Port Moresby accommodation (pre-tour)", description: "2 nights in POM before Wander tour starts Aug 14", stage: "planning", category: "accommodation", subcategory: "booking", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Investigar hoteles seguros en POM", requires_payment: true, estimated_amount: 120, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Port Moresby", notes: "Seguridad en POM — elegir hotel reconocido", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Book Port Moresby accommodation (post-tour)", description: "1 night in POM after tour ends Aug 20, before POM→MNL flight Aug 21", stage: "planning", category: "accommodation", subcategory: "booking", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Book same hotel as pre-tour if good", requires_payment: true, estimated_amount: 60, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Port Moresby", notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Book Manila transit accommodation (night 2)", description: "Hotel in MNL for night of Aug 21 after arriving from POM, before MNL→ICN", stage: "planning", category: "accommodation", subcategory: "booking", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Book same hotel as first MNL night", requires_payment: true, estimated_amount: 40, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Manila", notes: null, updated_at: new Date().toISOString() },

  // === DOCUMENTATION ===
  { trip_id: TRIP_ID, title: "Chequear validez del pasaporte (6+ meses)", description: "Que el pasaporte esté vigente hasta marzo 2027", stage: "planning", category: "documentation", subcategory: "passport", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-05-01", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: "Chequear fecha de vencimiento del pasaporte", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "PNG, Philippines, South Korea, UAE all require 6+ months validity", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Chequear requisitos de visa PNG para pasaporte argentino", description: "Ver si hay visa a la llegada o hay que tramitarla antes", stage: "planning", category: "documentation", subcategory: "visa", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-05-15", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: "Check PNG immigration website / embassy", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Port Moresby", notes: "requires_validation - may need to apply in advance", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Chequear visa/K-ETA Corea para pasaporte argentino", description: "Research K-ETA or visa requirements for 11-night stay", stage: "planning", category: "documentation", subcategory: "visa", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-05-15", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: "Check Korean embassy website", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "requires_validation", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Chequear requisitos de visa de tránsito en Filipinas", description: "Confirm if transit visa needed for Argentine passport at MNL", stage: "planning", category: "documentation", subcategory: "visa", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-05-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Check Philippine embassy", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Manila", notes: "Overnight stays in MNL may require entry visa", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Chequear requisitos de visa de tránsito UAE (Dubái)", description: "Confirm if DXB transit needs visa for Argentine passport", stage: "planning", category: "documentation", subcategory: "visa", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-05-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Check Emirates/UAE requirements", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Dubai", notes: "Transit only, may not need visa", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Escanear y respaldar todos los documentos", description: "Digital copies of passport, tickets, insurance, reservations", stage: "pre_departure", category: "documentation", subcategory: "backup", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-15", due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Save in cloud + offline copies on phone", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Preparar paquete offline de documentos", description: "Download/save all critical docs for offline access in PNG (no reliable internet)", stage: "pre_departure", category: "documentation", subcategory: "backup", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-01", due_date: "2026-08-07", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "PNG highlands have very limited connectivity", updated_at: new Date().toISOString() },

  // === HEALTH ===
  { trip_id: TRIP_ID, title: "Investigar vacunas requeridas para PNG", description: "Check required/recommended vaccines for PNG (yellow fever, malaria prophylaxis, etc.)", stage: "planning", category: "health", subcategory: "vaccinations", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-05-01", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: "Ir a clínica de medicina del viajero", requires_payment: true, estimated_amount: 100, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "PNG requires yellow fever cert if coming from endemic area. Malaria prophylaxis likely needed for highlands.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Ir a clínica de medicina del viajero", description: "Get vaccinations and malaria prophylaxis prescription", stage: "planning", category: "health", subcategory: "vaccinations", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-05-01", due_date: "2026-06-01", status: "pending", progress: 0, is_blocker: true, dependency_id: null, next_action: "Schedule appointment", requires_payment: true, estimated_amount: 150, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Some vaccines need 4-6 weeks to be effective", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Comprar profilaxis antimalárica", description: "Purchase prescribed antimalarial medication", stage: "planning", category: "health", subcategory: "medication", priority: "critical", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-06-01", due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: true, estimated_amount: 50, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Start taking before trip per doctor's instructions", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Preparar botiquín de primeros auxilios para PNG", description: "Assemble travel medical kit with basics + PNG-specific items", stage: "pre_departure", category: "health", subcategory: "supplies", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-01", due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Make list of needed items", requires_payment: true, estimated_amount: 40, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Include water purification, insect repellent DEET, ORS packets, antibiotics", updated_at: new Date().toISOString() },

  // === FINANCE ===
  { trip_id: TRIP_ID, title: "Avisar al banco de las fechas de viaje", description: "Inform credit/debit card issuers about travel to Philippines, PNG, UAE, South Korea", stage: "pre_departure", category: "finance", subcategory: "banking", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-15", due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Include Black card and all cards being carried", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Investigar necesidad de USD cash en PNG", description: "Determine how much USD cash to carry for PNG (limited ATMs in highlands)", stage: "planning", category: "finance", subcategory: "cash", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Research PNG payment landscape", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Port Moresby", notes: "PNG highlands: cash-based economy, no reliable ATMs", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Conseguir USD efectivo para el viaje", description: "Withdraw/exchange sufficient USD cash", stage: "pre_departure", category: "finance", subcategory: "cash", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-20", due_date: "2026-08-05", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: true, estimated_amount: 500, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "For PNG meals not included + POM meals + tips + emergencies", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Investigar dónde conseguir KRW", description: "Best way to get KRW: exchange in Buenos Aires, at ICN airport, or use cards", stage: "planning", category: "finance", subcategory: "currency", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Research best rates and methods", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "Seoul is very card-friendly, but some markets are cash-only", updated_at: new Date().toISOString() },

  // === CONNECTIVITY ===
  { trip_id: TRIP_ID, title: "Investigar eSIM/SIM para Corea", description: "Find best data plan for 11 days in Seoul", stage: "planning", category: "connectivity", subcategory: "sim", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Compare eSIM providers (Airalo, Holafly, etc.)", requires_payment: true, estimated_amount: 20, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Investigar conectividad en PNG", description: "Options for data/calls in PNG (if any)", stage: "planning", category: "connectivity", subcategory: "sim", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Ask Wander Expeditions about connectivity during tour", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "PNG Highlands", notes: "Very limited in highlands. May only have connectivity in POM.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Buy eSIM/SIM for South Korea", description: "Purchase data plan before departure", stage: "pre_departure", category: "connectivity", subcategory: "purchase", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-15", due_date: "2026-08-05", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: true, estimated_amount: 20, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: null, updated_at: new Date().toISOString() },

  // === ACTIVITIES / SEOUL PLANNING ===
  { trip_id: TRIP_ID, title: "Research Seoul must-visit spots", description: "Plan 11 days of activities in Seoul area", stage: "planning", category: "activities", subcategory: "research", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Research cultural sites, temples, markets, neighborhoods", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "Focus on authentic cultural experiences, off-the-beaten-path. No pop-culture tourism.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research Seoul day trips", description: "DMZ, Suwon Hwaseong, temples, etc.", stage: "planning", category: "activities", subcategory: "research", priority: "medium", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research Seoul food guide", description: "Must-try foods, Gwangjang Market specialties, budget-friendly eats", stage: "planning", category: "activities", subcategory: "food", priority: "medium", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "Gwangjang Market is walking distance from Airbnb", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research Seoul transport (T-money card, metro)", description: "How to get around Seoul efficiently", stage: "planning", category: "transport", subcategory: "research", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Research T-money card and metro system", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research ICN airport to Jongno Airbnb transport", description: "Best way to get from Incheon airport to accommodation", stage: "planning", category: "transport", subcategory: "research", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "AREX train vs bus vs taxi comparison", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: null, updated_at: new Date().toISOString() },

  // === WANDER EXPEDITIONS PREP ===
  { trip_id: TRIP_ID, title: "Review Wander Expeditions PNG III briefing materials", description: "Read all pre-trip documentation from Wander", stage: "planning", category: "activities", subcategory: "preparation", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Request briefing docs from Álvaro Rojas if not received", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "PNG Highlands", notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Prepare gifts for PNG host communities", description: "Research and buy appropriate gifts for Asaro Mudmen, Skeleton Tribe, Dust Walkers communities", stage: "pre_departure", category: "activities", subcategory: "preparation", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-01", due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Ask Wander what's appropriate", requires_payment: true, estimated_amount: 50, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "PNG Highlands", notes: "Ask Álvaro for recommendations on culturally appropriate gifts", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Confirm Wander Expeditions meeting point", description: "Confirm where and when to meet in Port Moresby on Aug 14", stage: "planning", category: "logistics", subcategory: "confirmation", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-15", due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Email Álvaro Rojas", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Port Moresby", notes: null, updated_at: new Date().toISOString() },

  // === PACKING RELATED ===
  { trip_id: TRIP_ID, title: "Research PNG packing list", description: "What to pack for highlands (weather, cultural considerations, terrain)", stage: "planning", category: "packing", subcategory: "research", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-06-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Ask Wander for recommended packing list", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "PNG Highlands", notes: "Two very different climates: tropical POM vs cooler highlands + humid Seoul", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Buy insect repellent (high DEET)", description: "For PNG malaria protection", stage: "pre_departure", category: "packing", subcategory: "purchase", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-01", due_date: "2026-07-30", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Buy high-DEET repellent", requires_payment: true, estimated_amount: 15, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Buy water purification tabs/filter", description: "For PNG highlands - no reliable clean water", stage: "pre_departure", category: "packing", subcategory: "purchase", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-01", due_date: "2026-07-30", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: true, estimated_amount: 20, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },

  // === LOGISTICS ===
  { trip_id: TRIP_ID, title: "Request vacation days (Aug 9 - Sep 3)", description: "26 days vacation request", stage: "planning", category: "admin", subcategory: "work", priority: "critical", criticality: "blocker", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-05-01", status: "done", progress: 100, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Vacation dates confirmed: Aug 9 - Sep 3, 2026", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Arrange pet/home care while traveling", description: "Setup care for home and any obligations during 24-day absence", stage: "pre_departure", category: "admin", subcategory: "personal", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-01", due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "requires_validation - depends on personal situation", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Set up auto-replies for work email/Slack", description: null, stage: "pre_departure", category: "admin", subcategory: "work", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-07", due_date: "2026-08-09", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },

  // === PHOTOGRAPHY ===
  { trip_id: TRIP_ID, title: "Prepare camera gear for PNG", description: "Check camera, lenses, memory cards, batteries, waterproof protection", stage: "pre_departure", category: "packing", subcategory: "photography", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-15", due_date: "2026-08-05", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Test all equipment", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Goroka Show is once-in-a-lifetime photography opportunity", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Buy extra memory cards and backup solution", description: "Sufficient storage for 24 days of heavy shooting", stage: "pre_departure", category: "packing", subcategory: "photography", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-01", due_date: "2026-07-30", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: true, estimated_amount: 40, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },

  // === SAFETY ===
  { trip_id: TRIP_ID, title: "Register with Argentine consulate (PNG + SK)", description: "Register travel with Argentine consulates in relevant countries", stage: "pre_departure", category: "documentation", subcategory: "safety", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-07-15", due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Check Cancillería registration portal", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Share itinerary with emergency contacts", description: "Send complete itinerary to family/friends for safety", stage: "pre_departure", category: "admin", subcategory: "safety", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-01", due_date: "2026-08-08", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Especially important for PNG leg", updated_at: new Date().toISOString() },

  // === TRANSPORT ===
  { trip_id: TRIP_ID, title: "Research POM airport to hotel transport", description: "How to safely get from Jacksons International to hotel in Port Moresby", stage: "planning", category: "transport", subcategory: "research", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Ask hotel about airport pickup", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Port Moresby", notes: "POM safety considerations - arrange hotel pickup", updated_at: new Date().toISOString() },

  // === PRE-DEPARTURE FINAL ===
  { trip_id: TRIP_ID, title: "Final packing check", description: "Complete packing checklist verification", stage: "pre_departure", category: "packing", subcategory: "final", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-07", due_date: "2026-08-09", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Charge all devices and power banks", description: null, stage: "pre_departure", category: "packing", subcategory: "electronics", priority: "medium", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-08", due_date: "2026-08-09", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Download offline maps (PNG + Seoul)", description: "Google Maps/Maps.me offline for both destinations", stage: "pre_departure", category: "connectivity", subcategory: "preparation", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-01", due_date: "2026-08-08", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Critical for PNG where connectivity is very limited", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Print critical documents", description: "Print boarding passes, insurance policy, emergency contacts, hotel confirmations", stage: "pre_departure", category: "documentation", subcategory: "print", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-07", due_date: "2026-08-09", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Paper copies essential for PNG immigration", updated_at: new Date().toISOString() },

  // === FLIGHT MONITORING ===
  { trip_id: TRIP_ID, title: "Update flight monitor to current routes", description: "Update Python/Flask flight monitoring system to track confirmed routes", stage: "planning", category: "admin", subcategory: "tech", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-06-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Update Railway deployment with new route parameters", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Flight monitor on Railway/Telegram. Currently monitoring old routes (EZE→TPE, EZE→LHR).", updated_at: new Date().toISOString() },

  // === ADDITIONAL PLANNING ===
  { trip_id: TRIP_ID, title: "Research Seoul August weather specifics", description: "Temperature, humidity, rain patterns for late Aug", stage: "planning", category: "activities", subcategory: "research", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "August is hot and humid. Rainy season possible.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research Seoul free/budget cultural activities", description: "Free palace entries, temple stays, traditional markets", stage: "planning", category: "activities", subcategory: "research", priority: "medium", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "Many palaces offer free entry for hanbok wearers", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research power adapters needed", description: "Check plug types for PNG (Type I) and South Korea (Type C/F)", stage: "planning", category: "packing", subcategory: "electronics", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Buy universal adapter if needed", requires_payment: true, estimated_amount: 15, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "PNG uses Australian-style Type I. Korea uses European-style Type C/F.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Backup phone data before trip", description: "Full backup of phone contacts, photos, apps", stage: "pre_departure", category: "admin", subcategory: "tech", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-01", due_date: "2026-08-08", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Learn basic Korean phrases", description: "Hello, thank you, excuse me, numbers, basic food ordering", stage: "planning", category: "activities", subcategory: "preparation", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: null, updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Learn basic Tok Pisin phrases", description: "Basic phrases for PNG communication", stage: "planning", category: "activities", subcategory: "preparation", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "PNG Highlands", notes: "Tok Pisin is PNG's lingua franca", updated_at: new Date().toISOString() },

  // === LONDON TRIP PREP ===
  { trip_id: TRIP_ID, title: "Note: London trip planned Sep-Oct 2026", description: "Separate London trip follows shortly after return. Plan packing/rest accordingly.", stage: "planning", category: "admin", subcategory: "planning", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: null, status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Plan buffer days between trips", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Separate trip planned for Sep-Oct 2026", updated_at: new Date().toISOString() },

  // === ADDITIONAL TASKS TO 72 ===
  { trip_id: TRIP_ID, title: "Research Seoul laundry options", description: "Find coin laundry or laundry services near Jongno Airbnb for 11-night stay", stage: "planning", category: "logistics", subcategory: "research", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "Can reduce packing if laundry available", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Check credit card travel benefits", description: "Review Black card travel insurance, lounge access, purchase protection", stage: "planning", category: "finance", subcategory: "benefits", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-06-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Call card issuer", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "May have complementary insurance or lounge access at DXB", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research Seoul Airbnb check-in process", description: "Understand keypad code or meet-up logistics for late arrival", stage: "planning", category: "accommodation", subcategory: "logistics", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Message Airbnb host about arrival time", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "May arrive late depending on MNL→ICN flight time", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Set daily budget alerts on phone", description: "Configure spending tracker notifications", stage: "pre_departure", category: "finance", subcategory: "tracking", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-01", due_date: "2026-08-08", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Use Travel OS expense module on mobile", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research DXB transit lounge options", description: "Emirates lounge access or rest areas during Dubai layover", stage: "planning", category: "logistics", subcategory: "transit", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Dubai", notes: "Check if Black card gives lounge access", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Prepare emergency cash reserve", description: "Separate emergency USD from daily spending cash", stage: "pre_departure", category: "finance", subcategory: "emergency", priority: "high", criticality: "essential", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-01", due_date: "2026-08-08", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: true, estimated_amount: 200, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Keep separate from daily wallet. For true emergencies only.", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Create trip photo/video backup plan", description: "Strategy for backing up photos during 24-day trip", stage: "planning", category: "admin", subcategory: "tech", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: "Research portable SSD or cloud backup options", requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Critical given Goroka Show once-in-a-lifetime shots", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research Seoul late-night food options near Jongno", description: "Late-night restaurants, convenience stores, delivery apps", stage: "planning", category: "food", subcategory: "research", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-08-01", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: "Seoul", notes: "Jongno area has many options", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Test all gear before departure", description: "Test camera, power bank, headlamp, water purification", stage: "pre_departure", category: "packing", subcategory: "testing", priority: "medium", criticality: "important", responsible: "Matias", created_at: new Date().toISOString(), start_date: "2026-08-01", due_date: "2026-08-07", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Don't discover broken gear in PNG highlands", updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, title: "Research tipping customs (PNG + Seoul)", description: "Understand tipping expectations in both destinations", stage: "planning", category: "finance", subcategory: "research", priority: "low", criticality: "nice_to_have", responsible: "Matias", created_at: new Date().toISOString(), start_date: null, due_date: "2026-07-15", status: "pending", progress: 0, is_blocker: false, dependency_id: null, next_action: null, requires_payment: false, estimated_amount: null, actual_amount: null, reservation_id: null, document_id: null, city_id: null, city_name: null, notes: "Different customs in each country", updated_at: new Date().toISOString() },
];

// ─── DOCUMENTS ───
export const seedDocuments: Omit<Document, "id">[] = [
  { trip_id: TRIP_ID, type: "passport", name: "Argentine Passport", criticality: "blocker", expiry_date: null, status: "pending", has_digital_copy: false, has_offline_copy: false, is_validated: false, action_required: "Verify 6+ months validity beyond Sep 2026", notes: "requires_validation - check expiry date", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "visa", name: "PNG Visa/Entry Permit", criticality: "blocker", expiry_date: null, status: "pending", has_digital_copy: false, has_offline_copy: false, is_validated: false, action_required: "Research visa requirements for Argentine passport", notes: "requires_validation", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "visa", name: "South Korea K-ETA/Visa", criticality: "blocker", expiry_date: null, status: "pending", has_digital_copy: false, has_offline_copy: false, is_validated: false, action_required: "Research K-ETA eligibility for Argentine passport", notes: "requires_validation", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "visa", name: "Philippines Entry Requirements", criticality: "essential", expiry_date: null, status: "pending", has_digital_copy: false, has_offline_copy: false, is_validated: false, action_required: "Check if overnight transit requires visa", notes: "Overnight in MNL before POM flight", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "insurance", name: "Travel Insurance Policy", criticality: "blocker", expiry_date: null, status: "pending", has_digital_copy: false, has_offline_copy: false, is_validated: false, action_required: "Purchase after confirming GOP for PNG", notes: "IATI Mochilero or Heymondo TOP. Must have direct GOP for medevac.", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "ticket", name: "Emirates GRU→DXB→MNL + ICN→DXB→GRU", criticality: "blocker", expiry_date: null, status: "ready", has_digital_copy: true, has_offline_copy: false, is_validated: true, action_required: "Save offline copy", notes: "Locator NM6XKS. Confirmed.", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "ticket", name: "PAL MNL→POM + Air Niugini POM→MNL", criticality: "blocker", expiry_date: null, status: "ready", has_digital_copy: true, has_offline_copy: false, is_validated: true, action_required: "Save offline copy", notes: "Booking 1124-604-505. Confirmed.", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "reservation", name: "Wander Expeditions PNG III Confirmation", criticality: "blocker", expiry_date: null, status: "ready", has_digital_copy: true, has_offline_copy: false, is_validated: true, action_required: "Save offline copy, get meeting point details", notes: "EUR 3,450. Zero refund within 90 days.", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "reservation", name: "Seoul Airbnb Confirmation", criticality: "essential", expiry_date: null, status: "ready", has_digital_copy: true, has_offline_copy: false, is_validated: true, action_required: "Confirm AC with host. Save offline copy.", notes: "Jongno district, 11 nights.", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "medical", name: "Vaccination Certificate", criticality: "blocker", expiry_date: null, status: "pending", has_digital_copy: false, has_offline_copy: false, is_validated: false, action_required: "Ir a clínica de medicina del viajero", notes: "Yellow fever cert may be required for PNG", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "medical", name: "Malaria Prophylaxis Prescription", criticality: "essential", expiry_date: null, status: "pending", has_digital_copy: false, has_offline_copy: false, is_validated: false, action_required: "Get prescription from travel clinic", notes: null, attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "emergency_contact", name: "Emergency Contacts List", criticality: "essential", expiry_date: null, status: "pending", has_digital_copy: false, has_offline_copy: false, is_validated: false, action_required: "Compile list with local emergency numbers for each country", notes: "Include: Argentine consulates, Wander Expeditions contact, Airbnb host, insurance hotline", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "payment_method", name: "Black Credit Card", criticality: "essential", expiry_date: null, status: "ready", has_digital_copy: false, has_offline_copy: false, is_validated: true, action_required: "Notify bank of travel dates", notes: "Primary payment card", attachment_url: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

// ─── PACKING ITEMS ───
export const seedPackingItems: Omit<PackingItem, "id">[] = [
  // Clothing
  { trip_id: TRIP_ID, category: "clothing", subcategory: "tops", item: "Lightweight breathable t-shirts", quantity_target: 6, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "high", status: "pending", deadline: "2026-08-05", notes: "Quick-dry material for PNG humidity + Seoul heat" },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "tops", item: "Long-sleeve sun protection shirt", quantity_target: 2, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "high", status: "pending", deadline: "2026-08-05", notes: "For PNG sun/insects" },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "bottoms", item: "Convertible hiking pants", quantity_target: 2, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "high", status: "pending", deadline: "2026-08-05", notes: "For PNG treks" },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "bottoms", item: "Lightweight casual pants", quantity_target: 2, quantity_current: 0, is_essential: false, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "medium", status: "pending", deadline: "2026-08-05", notes: "For Seoul" },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "bottoms", item: "Shorts", quantity_target: 2, quantity_current: 0, is_essential: false, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "medium", status: "pending", deadline: "2026-08-05", notes: null },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "underwear", item: "Underwear", quantity_target: 8, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "high", status: "pending", deadline: "2026-08-05", notes: "Quick-dry" },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "underwear", item: "Socks (hiking + casual)", quantity_target: 6, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "high", status: "pending", deadline: "2026-08-05", notes: null },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "footwear", item: "Hiking boots/shoes", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "wear", priority: "critical", status: "pending", deadline: "2026-08-05", notes: "Essential for PNG highland terrain" },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "footwear", item: "Comfortable walking shoes", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "high", status: "pending", deadline: "2026-08-05", notes: "For Seoul urban walking" },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "footwear", item: "Flip flops/sandals", quantity_target: 1, quantity_current: 0, is_essential: false, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "low", status: "pending", deadline: "2026-08-05", notes: null },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "outerwear", item: "Rain jacket (packable)", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-08-05", notes: "PNG highlands rain + Seoul monsoon season" },
  { trip_id: TRIP_ID, category: "clothing", subcategory: "outerwear", item: "Light fleece/sweater", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "medium", status: "pending", deadline: "2026-08-05", notes: "PNG highlands can be cool at night" },

  // Electronics
  { trip_id: TRIP_ID, category: "electronics", subcategory: "power", item: "Universal power adapter", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "daypack", priority: "critical", status: "pending", deadline: "2026-07-30", notes: "Type I (PNG/AU) + Type C/F (Korea)" },
  { trip_id: TRIP_ID, category: "electronics", subcategory: "power", item: "Power bank (20000+ mAh)", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "critical", status: "pending", deadline: "2026-08-05", notes: "Essential for PNG where charging is limited" },
  { trip_id: TRIP_ID, category: "electronics", subcategory: "power", item: "USB cables and chargers", quantity_target: 3, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-08-05", notes: null },
  { trip_id: TRIP_ID, category: "electronics", subcategory: "devices", item: "Phone", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "carry", priority: "critical", status: "pending", deadline: "2026-08-09", notes: null },
  { trip_id: TRIP_ID, category: "electronics", subcategory: "devices", item: "Headphones", quantity_target: 1, quantity_current: 0, is_essential: false, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "medium", status: "pending", deadline: "2026-08-05", notes: "For long flights" },

  // Health
  { trip_id: TRIP_ID, category: "health", subcategory: "medication", item: "Malaria prophylaxis pills", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "daypack", priority: "critical", status: "pending", deadline: "2026-07-30", notes: "Start taking before departure per prescription" },
  { trip_id: TRIP_ID, category: "health", subcategory: "protection", item: "DEET insect repellent", quantity_target: 2, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "main", priority: "critical", status: "pending", deadline: "2026-07-30", notes: "High concentration DEET for PNG malaria areas" },
  { trip_id: TRIP_ID, category: "health", subcategory: "protection", item: "Sunscreen SPF 50+", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-07-30", notes: null },
  { trip_id: TRIP_ID, category: "health", subcategory: "water", item: "Water purification tablets", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "daypack", priority: "critical", status: "pending", deadline: "2026-07-30", notes: "No reliable clean water in PNG highlands" },
  { trip_id: TRIP_ID, category: "health", subcategory: "first-aid", item: "First aid kit", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "main", priority: "high", status: "pending", deadline: "2026-07-30", notes: "Include ORS packets, antibiotics, wound care" },
  { trip_id: TRIP_ID, category: "health", subcategory: "medication", item: "Personal medications", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "critical", status: "pending", deadline: "2026-08-05", notes: "requires_validation - depends on personal needs" },

  // Gear
  { trip_id: TRIP_ID, category: "gear", subcategory: "bags", item: "Daypack (25-30L)", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "carry-on", priority: "high", status: "pending", deadline: "2026-08-05", notes: "For day trips in both PNG and Seoul" },
  { trip_id: TRIP_ID, category: "gear", subcategory: "rain", item: "Dry bags/waterproof pouches", quantity_target: 2, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-07-30", notes: "Protect electronics in PNG rain" },
  { trip_id: TRIP_ID, category: "gear", subcategory: "light", item: "Headlamp", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-08-05", notes: "No reliable electricity in PNG highland homestays" },
  { trip_id: TRIP_ID, category: "gear", subcategory: "hydration", item: "Reusable water bottle", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-08-05", notes: null },

  // Toiletries
  { trip_id: TRIP_ID, category: "toiletries", subcategory: "basics", item: "Toiletry bag (travel size)", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "main", priority: "medium", status: "pending", deadline: "2026-08-05", notes: null },
  { trip_id: TRIP_ID, category: "toiletries", subcategory: "basics", item: "Hand sanitizer", quantity_target: 2, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-07-30", notes: "Essential for PNG where water may not be available for handwashing" },

  // Documents (physical)
  { trip_id: TRIP_ID, category: "documents", subcategory: "travel", item: "Passport", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "carry", priority: "critical", status: "pending", deadline: "2026-08-09", notes: null },
  { trip_id: TRIP_ID, category: "documents", subcategory: "travel", item: "Printed copies of all bookings", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "carry", priority: "critical", status: "pending", deadline: "2026-08-09", notes: "Paper copies essential for PNG immigration" },
  { trip_id: TRIP_ID, category: "documents", subcategory: "finance", item: "Credit cards (Black + backup)", quantity_target: 2, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "carry", priority: "critical", status: "pending", deadline: "2026-08-09", notes: null },
  { trip_id: TRIP_ID, category: "documents", subcategory: "finance", item: "USD cash", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "carry", priority: "critical", status: "pending", deadline: "2026-08-05", notes: "For PNG cash-based economy" },

  // Photography
  { trip_id: TRIP_ID, category: "photography", subcategory: "camera", item: "Camera body", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "critical", status: "pending", deadline: "2026-08-05", notes: "Goroka Show = major photography opportunity" },
  { trip_id: TRIP_ID, category: "photography", subcategory: "camera", item: "Camera lenses", quantity_target: 2, quantity_current: 0, is_essential: true, is_purchased: true, needs_purchase: false, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-08-05", notes: null },
  { trip_id: TRIP_ID, category: "photography", subcategory: "storage", item: "Memory cards (64GB+)", quantity_target: 4, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-07-30", notes: null },
  { trip_id: TRIP_ID, category: "photography", subcategory: "accessories", item: "Camera rain cover", quantity_target: 1, quantity_current: 0, is_essential: true, is_purchased: false, needs_purchase: true, assigned_bag: "daypack", priority: "high", status: "pending", deadline: "2026-07-30", notes: "PNG highlands rain protection" },
];

// ─── EXPENSES (pre-trip purchases already made) ───
export const seedExpenses: Omit<Expense, "id">[] = [
  {
    trip_id: TRIP_ID, date: "2026-04-01", city_id: null, city_name: null,
    category: "flights", subcategory: "international",
    description: "Emirates GRU→DXB→MNL + ICN→DXB→GRU (NM6XKS)",
    payment_method: "credit_card_black", original_currency: "BRL",
    original_amount: 9940, exchange_rate: 5.16, base_amount: 1927,
    is_fixed: true, is_budgeted: true, reservation_id: null,
    attachment_url: null, notes: "Turista Flex fare", created_at: new Date().toISOString(),
  },
  {
    trip_id: TRIP_ID, date: "2026-04-01", city_id: null, city_name: null,
    category: "flights", subcategory: "regional",
    description: "PAL MNL→POM + Air Niugini POM→MNL (1124-604-505)",
    payment_method: "credit_card_other", original_currency: "ARS",
    original_amount: 734710, exchange_rate: 1200, base_amount: 612,
    is_fixed: true, is_budgeted: true, reservation_id: null,
    attachment_url: null, notes: "Flex fare", created_at: new Date().toISOString(),
  },
  {
    trip_id: TRIP_ID, date: "2026-01-15", city_id: null, city_name: null,
    category: "activities", subcategory: "tour",
    description: "Wander Expeditions PNG III Tour deposit/payment",
    payment_method: "bank_transfer", original_currency: "EUR",
    original_amount: 3450, exchange_rate: 0.926, base_amount: 3726,
    is_fixed: true, is_budgeted: true, reservation_id: null,
    attachment_url: null, notes: "EUR 3,450. Non-refundable within 90 days.", created_at: new Date().toISOString(),
  },
];

// ─── ALERTS (initial set based on current state) ───
export const seedAlerts: Omit<Alert, "id">[] = [
  { trip_id: TRIP_ID, type: "reservation_critical_pending", severity: "critical", module: "reservations", origin_id: null, title: "Vuelo BUE↔GRU sin reservar", description: "Tramo crítico Buenos Aires↔São Paulo todavía sin comprar. Deadline: 15 jun.", detected_at: new Date().toISOString(), target_date: "2026-06-15", status: "active", suggested_action: "Reservar con puntos de TC", deep_link: "/reservations", created_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "reservation_critical_pending", severity: "critical", module: "reservations", origin_id: null, title: "MNL→ICN flight not booked", description: "Manila to Seoul flight not yet purchased. Deadline: Jun 30.", detected_at: new Date().toISOString(), target_date: "2026-06-30", status: "active", suggested_action: "Compare prices and purchase", deep_link: "/reservations", created_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "reservation_critical_pending", severity: "critical", module: "reservations", origin_id: null, title: "Travel insurance not purchased", description: "No travel insurance purchased. Must confirm GOP for PNG medevac before buying.", detected_at: new Date().toISOString(), target_date: "2026-07-15", status: "active", suggested_action: "Research IATI/Heymondo, confirm GOP, purchase", deep_link: "/reservations", created_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "doc_critical_missing", severity: "critical", module: "documents", origin_id: null, title: "PNG visa status unknown", description: "Visa requirements for Argentine passport entering PNG not yet verified.", detected_at: new Date().toISOString(), target_date: "2026-05-15", status: "active", suggested_action: "Check PNG immigration requirements", deep_link: "/documents", created_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "doc_critical_missing", severity: "critical", module: "documents", origin_id: null, title: "South Korea K-ETA status unknown", description: "K-ETA or visa requirements for Argentine passport not yet verified.", detected_at: new Date().toISOString(), target_date: "2026-05-15", status: "active", suggested_action: "Check Korean embassy website", deep_link: "/documents", created_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "task_critical_not_started", severity: "critical", module: "tasks", origin_id: null, title: "Vaccinations not started", description: "PNG vaccination requirements not researched. Some vaccines need 4-6 weeks to be effective.", detected_at: new Date().toISOString(), target_date: "2026-05-01", status: "active", suggested_action: "Ir a clínica de medicina del viajero", deep_link: "/tasks", created_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "night_uncovered", severity: "warning", module: "itinerary", origin_id: null, title: "Manila nights without accommodation", description: "2 overnight stays in Manila (Aug 11 and Aug 21) without hotel booked.", detected_at: new Date().toISOString(), target_date: "2026-07-01", status: "active", suggested_action: "Book MNL airport hotel for transit nights", deep_link: "/reservations", created_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "night_uncovered", severity: "warning", module: "itinerary", origin_id: null, title: "Port Moresby nights without accommodation", description: "3 nights in POM (pre/post tour) without hotel booked.", detected_at: new Date().toISOString(), target_date: "2026-07-01", status: "active", suggested_action: "Book POM hotel for pre/post tour nights", deep_link: "/reservations", created_at: new Date().toISOString() },
  { trip_id: TRIP_ID, type: "packing_not_purchased", severity: "warning", module: "packing", origin_id: null, title: "Essential items need purchasing", description: "Multiple essential items not yet purchased: universal adapter, DEET repellent, water purification, first aid kit, memory cards.", detected_at: new Date().toISOString(), target_date: "2026-07-30", status: "active", suggested_action: "Create shopping list and purchase", deep_link: "/packing", created_at: new Date().toISOString() },
];

export function getTripId() { return TRIP_ID; }
